### ISSUE TITLE
Nix support

### ISSUE THREAD

**Issue by Ahwxorg** [KZDKM/Hyswipe#1]
Will there be Nix support similarly to [Hyprspace](https://github.com/KZDKM/Hyprspace)?

**Comment by KZDKM** [comment]
Oh hi, didn't know that this project is also getting attention. Unfortunately I dont have experience with nix and nix support for hyprspace is maintained by other contributors. You can try to ping them to see if they are willing to make it happen for this plugin.

**Comment by Ahwxorg** [comment]
Hereby pinging those who seem to be contributors/maintainers: @matt1432 / @zkyzx / @dmadisetti / @Harbiinger.

**Comment by matt1432** [comment]
I made a PR here: https://github.com/KZDKM/Hyswipe/pull/2

**Comment by Ahwxorg** [comment]
Thank you a lot!

**Comment by Ahwxorg** [comment]
I do get the following error:

![image](https://github.com/user-attachments/assets/f45db9dd-e4c9-4c6a-a311-edb550e647a5)

Plugins in Hyprland are declared like so:

![image](https://github.com/user-attachments/assets/fead2d5f-9747-42bf-8032-5d88dcb73079)

My flake.nix is declared like so:

![image](https://github.com/user-attachments/assets/aef57b8a-1d61-4e41-b6a6-331e01c1b299)

Hyprspace works perfectly fine

**Comment by matt1432** [comment]
Huh, that is really weird. I can make a PR to fix it right now

**Comment by matt1432** [comment]
@Ahwxorg it should work now

**Comment by Ahwxorg** [comment]
Yes it does, sorry, should've reported back! Works great!
